### ISSUE TITLE
Notifications with chart not working for new bots

### ISSUE THREAD

**Issue by ant0lik** [qa-guru/allure-notifications#311] opened 2024-09-27 17:02 UTC
How to reproduce:
1. Create a new bot in Slack
2. Set 'enableChart' to true in config.json
3. Send the report 
`java "-DconfigFile=notifications/config.json" -jar notifications/allure-notifications-4.7.0.jar`

Output:
...
===RESPONSE===
STATUS CODE: 200
BODY: 
{
  "ok": false,
  "error": "method_deprecated",
  "warning": "superfluous_charset",
  "response_metadata": {
    "warnings": [
      "superfluous_charset"
    ]
  }
}

As a result, message is not sent to Slack (as I understand it's because files.upload is deprecated in Slack and no longer works for new bots)

Please let me know when you are going to fix it
Thanks

**Comment by valfirst** [comment] 2024-09-30 07:27
Duplicate of #273

**Closed by valfirst** 2024-09-30 07:27 UTC
